plugins:
  - rubocop-sorted_methods_by_call
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/DoubleNegation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/irb-autosuggestions.rb

Metrics/ModuleLength:
  Max: 110

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
