plugins:
  - rubocop-sorted_methods_by_call
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/DoubleNegation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Metrics/ModuleLength:
  Max: 105

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
