module Irb
  module Autosuggestions
    module LineEditorPatch
      GRAY: String
      RESET: String

      def input_key: (untyped key) -> untyped
      def render: (*untyped) -> untyped
      def right_arrow?: (untyped key) -> bool
      def ghost_for: (String buffer) -> (String | nil)
      def render_ghost: (String ghost) -> void
      def write_extra_ghost_lines: (Array[String] lines) -> void
      def restore_cursor_after: (Array[String] lines) -> void
      def find_suggestion: (String buffer) -> (String | nil)
      def accept_suggestion: (String suggestion) -> void
    end
  end
end
